name: Logvue Build

env:
  GITHUB_DEPLOY: 'false'

on:
  pull_request:
    branches:
      - main
      - rel_*
    paths-ignore:
      - LICENSE
      - README.md
      - 'docs/**'
      - '.github/config/labels.yml'

  workflow_dispatch:
  repository_dispatch:
    types: [ app-release ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build Package
    timeout-minutes: 15
    continue-on-error: false
    # if: github.event_name  == 'pull_request'

    runs-on: ${{ matrix.os }}
    environment: PreProd
    env:
      SENTRY_ENDPOINT: ${{ secrets.SENTRY_ENDPOINT }}
      SENTRY_DEBUG: ${{ secrets.SENTRY_DEBUG }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        jdk: [ 18 ]

    steps:
      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Download ${{ matrix.os }} OpenJDK ${{ matrix.jdk }}
        id: download-jdk
        uses: sormuras/download-jdk@v1
        with:
          feature: ${{ matrix.jdk }}

      - name: Set up OpenJDK ${{ matrix.jdk }}
        id: setup-java
        uses: actions/setup-java@v2
        if: always() && steps.download-jdk.outcome == 'success'
        with:
          distribution: jdkfile
          java-version: ${{ env.JDK_VERSION }}
          jdkFile: ${{ env.JDK_FILE }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle Build
        id: gradle-build
        run: ./gradlew repackageUberJar package -PSENTRY_ENDPOINT=${{ env.SENTRY_ENDPOINT }}

      - name: Uploading ${{ matrix.os }} uber jar
        if: steps.gradle-build.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.gradle-build.outputs.uber_jar_name }}
          path: |
            ${{ steps.gradle-build.outputs.uber_jar_path }}
          if-no-files-found: error

      - name: Uploading ${{ matrix.os }} native package
        if: steps.gradle-build.outcome == 'success'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.gradle-build.outputs.app_pkg_name }}
          path: |
            ${{ steps.gradle-build.outputs.app_pkg_path }}
          if-no-files-found: error